### ISSUE TITLE
Support YAML, TOML, JSON

### ISSUE THREAD

**Issue by rochacbruno** [marczellm/tkpf#13]
I like the idea, but not XML

All the attributes in the XML can be expressed in to YAML or JSON

Using `xmltodict.unparse`  it is possible to transform YAML to dict then to XML.

**Comment by marczellm** [comment]
Hi and thank you for the suggestion! Yes, XML is a verbose format, and I've thought about this. I didn't go with another format for three reasons:

1. I'm not familiar with them
2. I've never seen a GUI framework using them successfully (I'd appreciate a few pointers)
3. I've seen successful GUI frameworks using XML: Android, WPF and React Native. Also the current trend of web frameworks like React and Angular have no trouble using HTML templates that are no less verbose.

**Comment by marczellm** [comment]
Also while in the strictest sense it's true that you can express anything in JSON, it still seems like a bit of a hack to represent attributes and body text with [special syntax](https://github.com/martinblech/xmltodict) in the key string:

`{"plus": {
            "@a": "complex", 
            "#text": "element as well"
        }}`

**Comment by rochacbruno** [comment]
Take a look at KV language used in Kivy https://kivy.org/docs/guide/lang.html

```xml
<MyFirstWidget>:
    # both these variables can be the same name and this doesn't lead to
    # an issue with uniqueness as the id is only accessible in kv.
    txt_inpt: txt_inpt
    Button:
        id: f_but
    TextInput:
        id: txt_inpt
        text: f_but.state
        on_text: root.check_status(f_but)
```

then

```python
class MyFirstWidget(BoxLayout):

    txt_inpt = ObjectProperty(None)

    def check_status(self, btn):
        print('button state is: {state}'.format(state=btn.state))
        print('text input text is: {txt}'.format(txt=self.txt_inpt))
```

**Comment by rochacbruno** [comment]
or look Ansible playbook YAML patterns

```yaml
Frame:
    pack: 
        anchor: nw
        padx: 5
    content:
        LabelFrame:
            pack: anchor=w fill=x
            text: Options
            content:
                RadioButton:
                   pack: anchor=w
                   variable: [(choice)]
                   value: option1
    
    

```
